[package]
name = "k2tree"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
num-traits = "0.2"
pdqselect = "0.1"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
#panic = "abort"
